src/Database/Entity/User.php
<?php

namespace Athorrent\Database\Entity;

use Athorrent\Cache\KeyGenerator\CacheKeyGetterInterface;
use Athorrent\Database\Repository\UserRepository;
use Athorrent\Database\Type\UserRole;
use DateTimeImmutable;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Cache;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Filesystem\Path;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'username', columns: ['username'])]
#[ORM\UniqueConstraint(name: 'port', columns: ['port'])]
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['username'], message: 'error.usernameAlreadyUsed')]
#[Cache(usage: 'NONSTRICT_READ_WRITE')]
class User implements UserInterface, PasswordAuthenticatedUserInterface, CacheKeyGetterInterface
{
    #[ORM\Id]
    #[ORM\Column(type: 'integer', options: ['unsigned' => true])]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    private int $id;

    #[NotBlank]
    #[Length(max: 32)]
    #[ORM\Column(length: 32)]
    private string $username;

    #[ORM\Column(type: 'text')]
    private string $password;

    #[ORM\Column(length: 32, nullable: true, options: ['fixed' => true])]
    private string $salt;

    #[ORM\Column]
    private DateTimeImmutable $creationDateTime;

    #[ORM\Column(nullable: true)]
    private ?DateTimeImmutable $connectionDateTime = null;

    /**
     * @var UserHasRole[]|Collection
     */
    #[ORM\OneToMany(targetEntity: 'UserHasRole', mappedBy: 'user', cascade: ['persist', 'detach'], fetch: 'EAGER')]
    #[Cache(usage: 'READ_ONLY')]
    private array|Collection $hasRoles;

    /**
     * @var Sharing[]|Collection
     */
    #[ORM\OneToMany(targetEntity: 'Sharing', mappedBy: 'user', indexBy: 'token', cascade: ['detach'], fetch: 'LAZY')]
    #[Cache(usage: 'NONSTRICT_READ_WRITE')]
    private array|Collection $sharings;

    #[ORM\Column]
    private int $port;

    public function __construct()
    {
        $this->creationDateTime = new DateTimeImmutable();
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getUserIdentifier(): string
    {
        return $this->username;
    }

    public function getUsername(): string
    {
        return $this->username;
    }

    public function setUsername(string $username): void
    {
        $this->username = $username;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): void
    {
        $this->password = $password;
    }

    public function getSalt(): ?string
    {
        return $this->salt;
    }

    public function setSalt(string $salt): void
    {
        $this->salt = $salt;
    }

    public function getCreationTimestamp(): int
    {
        return $this->creationDateTime->getTimestamp();
    }

    public function getConnectionTimestamp(): int
    {
        if ($this->connectionDateTime instanceof DateTimeImmutable) {
            return $this->connectionDateTime->getTimestamp();
        }

        return 0;
    }

    public function setConnectionDateTime(DateTimeImmutable $dateTime): void
    {
        $this->connectionDateTime = $dateTime;
    }

    /**
     * @return UserHasRole[]|Collection
     */
    public function getHasRoles(): array|Collection
    {
        return $this->hasRoles;
    }

    /**
     * @return string[]
     */
    public function getRoles(): array
    {
        $roles = [];

        foreach ($this->hasRoles as $hasRole) {
            $roles[] = $hasRole->getRole()->value;
        }

        return $roles;
    }

    /**
     * @param string[]|UserRole[] $roles
     */
    public function setRoles(array $roles): void
    {
        $this->hasRoles = array_map(fn($role) => new UserHasRole($this, UserRole::fromOrSelf($role)), $roles);
    }

    /**
     * @return Sharing[]|Collection
     */
    public function getSharings(): array|Collection
    {
        return $this->sharings;
    }

    public function getPort(): int
    {
        return $this->port;
    }

    public function setPort(int $port): void
    {
        $this->port = $port;
    }

    #[\Deprecated]
    public function eraseCredentials(): void
    {
    }

    public function __serialize(): array
    {
        $data = (array) $this;
        $data["\0".self::class."\0password"] = hash('crc32c', $this->password);

        return $data;
    }

    public function getCacheKey(): string
    {
        return (string)$this->id;
    }

    public function getPath(string $path): string
    {
        return Path::join(USER_ROOT_DIR, $this->id, $path);
    }

    public function getBackendPath(string $path = ''): string
    {
        return $this->getPath(Path::join('backend', $path));
    }

    public function getFilesPath(): string
    {
        return $this->getBackendPath('files');
    }

    public function getNewTorrentsPath(): string
    {
        return $this->getBackendPath('new-torrents');
    }

    public static function as(mixed $user): static
    {
        assert(
            $user instanceof static,
            sprintf('$user should be an instance of %s found %s instead', static::class, is_object($user) ? get_class($user) : gettype($user)),
        );

        return $user;
    }
}

templates/pages/addUser.html.twig
{% extends 'skeleton.html.twig' %}

{% block title %}{{ 'users.add.title'|trans }} - {{ 'app.name'|trans }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>{{ 'users.add.title'|trans }}</h1>
    </div>

    {{ form(form) }}
{% endblock %}

templates/pages/administration.html.twig
{% extends 'skeleton.html.twig' %}

{% block title %}{{ 'administration.title'|trans }} - {{ 'app.name'|trans }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('administration') }}
{% endblock %}

{% block content %}
{% cache cache_key('administration') %}
<h1>{{ 'administration.title'|trans }}</h1>
<hr />

<div>
    <a class="btn btn-default administration-tile" href="{{ path('listUsers') }}">
        <span class="fa fa-fw fa-user"></span>
        {{ 'administration.handleUsers'|trans }}
    </a>
</div>

{% endcache %}
{% endblock %}

templates/pages/displayFile.html.twig
{% extends 'skeleton.html.twig' %}

{% block title %}{{ name }} - {{ 'app.name'|trans }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('media') }}
{% endblock %}

{% block content %}
<h1 title="{{ name }}">{{ name }}</h1>
{% include 'fragments/breadcrumb.html.twig' %}
{% if text is defined %}
    <pre>{{ text }}</pre>
{% elseif src is defined %}
    <div class="media-container">
        <img src="{{ path('openFile', { path: src }) }}" />
    </div>
{% endif %}
{% endblock %}

templates/pages/editAccount.html.twig
{% extends 'skeleton.html.twig' %}

{% block title %}{{ 'account.edit.title'|trans }} - {{ 'app.name'|trans }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>{{ 'account.edit.title'|trans }}</h1>
    </div>

    {% form_theme form 'fragments/editAccount-form-layout.html.twig' %}
    {{ form(form) }}
{% endblock %}

templates/pages/error.html.twig
{% extends 'skeleton.html.twig' %}

{% block title %}{{ 'error.title'|trans }} {{ code }} - {{ 'app.name'|trans }}{% endblock %}

{% block content %}
    <div class="jumbotron">
        <h1>{{ 'error.title'|trans }} {{ code }}</h1>
        <p>{{ error }}</p>
    </div>
{% endblock %}

templates/pages/home.html.twig
{% extends 'skeleton.html.twig' %}

{% block title %}{{ 'app.name'|trans }} - {{ 'home.title'|trans }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('home') }}
{% endblock %}

{% block content %}
{% if error is defined and error is not empty %}
    <div class="alert alert-danger" role="alert">{{ error|trans }}</div>
{% endif %}

{% cache cache_key('home') %}
    <div class="jumbotron">
        <picture>
            <source srcset="{{ asset('build/logo-narrow.png') }}" media="(max-width: 767px)" />
            <img class="logo" src="{{ asset('build/logo-wide.png') }}" alt="{{ 'app.logo'|trans }}" />
        </picture>
        <div class="jumbotron-text">
            <h1>{{ 'home.welcome'|trans }}</h1>
            <p>{{ 'home.description'|trans|nl2br }}</p>
        </div>
    </div>

    <div class="block">
        <span class="fa fa-fw fa-user"></span>
        <div class="block-text">
            <h2>{{ 'home.accessibility.title'|trans }}</h2>
            <p>{{ 'home.accessibility.content'|trans }}</p>
        </div>
    </div>

    <div class="block">
        <span class="fa fa-fw fa-share"></span>
        <div class="block-text">
            <h2>{{ 'home.sharing.title'|trans }}</h2>
            <p>{{ 'home.sharing.content'|trans }}</p>
        </div>
    </div>

    <div class="block">
        <span class="fa fa-fw fa-lock"></span>
        <div class="block-text">
            <h2>{{ 'home.security.title'|trans }}</h2>
            <p>{{ 'home.security.content'|trans }}</p>
        </div>
    </div>

    <div class="block">
        <span class="fa fa-fw fa-wrench"></span>
        <div class="block-text">
            <h2>{{ 'home.performance.title'|trans }}</h2>
            <p>{{ 'home.performance.content'|trans }}</p>
        </div>
    </div>

    <div class="block">
        <span class="fab fa-fw fa-github"></span>
        <div class="block-text">
            <h2>{{ 'home.openSource.title'|trans }}</h2>
            <p>{{ 'home.openSource.content'|trans({ 'a_start': '<a href="https://github.com/Athorcis/athorrent-frontend">', 'a_end': '</a>'})|raw }}</p>
        </div>
    </div>
    {% endcache %}
{% endblock %}

templates/pages/listFiles.html.twig
{% extends 'skeleton.html.twig' %}

{% block title %}{% if title %}{{ title }}{% else %}Fichiers{% endif %} - {{ 'app.name'|trans }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('files') }}
{% endblock %}

{% block main_script %}
    {{ encore_entry_script_tags('files') }}
{% endblock %}

{% block content %}
    <h1 title="{{ title}}">{{ title }}</h1>

    {% include 'fragments/breadcrumb.html.twig' %}

    <table class="file-list">
        {% include 'fragments/listFiles.html.twig' %}
    </table>
{% endblock %}

templates/pages/listSharings.html.twig
{% extends 'skeleton.html.twig' %}

{% block title %}{{ 'sharings.title'|trans }} - {{ 'app.name'|trans }}{% endblock %}

{% block main_script %}
    {{ encore_entry_script_tags('sharings') }}
{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>{{ 'sharings.title'|trans }}</h1>
    </div>

    {% set sharings = pagination.entities %}

    {% if sharings|length == 0 %}
        <div class="alert alert-info" role="alert">{{ 'sharings.none'|trans }}</div>
    {% else %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>{{ 'sharings.path'|trans }}</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for sharing in sharings %}
                    {% cache cache_key('sharing', sharing) %}
                    <tr class="sharing" id="sharing-{{ sharing.token }}">
                        <td class="user-name">
                            <a href="{{ path('listFiles', { token: sharing.token, _prefixId: 'sharings' }) }}">{{ sharing.path }}</a>
                        </td>
                        <td class="text-right">
                            <button class="btn btn-xs btn-danger sharing-remove">
                                <span class="fa fa-times"></span>
                            </button>
                        </td>
                    </tr>
                    {% endcache %}
                {% endfor %}
            </tbody>
        </table>
    {% endif %}

    {% include "fragments/pagination.html.twig" %}

{% endblock %}

templates/pages/listTorrents.html.twig
{% extends "skeleton.html.twig" %}

{% block title %}{{ 'torrents.title'|trans }} - {{ 'app.name'|trans }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('torrents') }}
{% endblock %}

{% block main_script %}
    {{ encore_entry_script_tags('torrents') }}
{% endblock %}

{% block content %}
{% include "fragments/addTorrents.html.twig" %}
    <h1>{{ 'torrents.title'|trans }}</h1>

    <div class="torrent-list">
        {% include "fragments/listTorrents.html.twig" %}
    </div>

    <div class="torrent-panel panel-fixed-bottom">
        <ul class="nav nav-tabs">
            {#<li role="presentation"><a href="#torrent-general">{{ 'torrents.tabMain.title'|trans }}</a></li>#}
            <li role="presentation"  class="active"><a href="#torrent-trackers">{{ 'torrents.tabTrackers.title'|trans }}</a></li>
            <li role="presentation"><a href="#torrent-peers">{{ 'torrents.tabPeers.title'|trans }}</a></li>
        </ul>

        <div class="tab-content">
            {#<div role="tabpanel" class="tab-pane" id="torrent-general">...</div>#}
            <div role="tabpanel" class="tab-pane active" id="torrent-trackers"></div>
            <div role="tabpanel" class="tab-pane" id="torrent-peers">...</div>
        </div>
    </div>
{% endblock %}

{% block templates %}
    {{ parent() }}

    <template id="template-dropzone-preview">
        {% include "fragments/dropzonePreview.html.twig" %}
    </template>
{% endblock %}

templates/pages/listUsers.html.twig
{% extends 'skeleton.html.twig' %}

{% block title %}{{ 'users.title'|trans }} - {{ 'app.name'|trans }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('users') }}
{% endblock %}

{% block main_script %}
    {{ encore_entry_script_tags('users') }}
{% endblock %}

{% set userId = app.user.id %}

{% block content %}
    <div class="page-header">
        <h1>
            {{ 'users.title'|trans }}
            <a class="btn btn-default pull-right" href="{{ path('addUser') }}">{{ 'users.add.title'|trans }}</a>
        </h1>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>{{ 'users.username'|trans }}</th>
                <th>{{ 'users.role'|trans }}</th>
                <th>{{ 'users.lastConnection'|trans }}</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for user in pagination.entities %}
                {% cache cache_key('user', user) %}
                <tr class="user" id="user-{{ user.id }}">
                    <td>{{ user.id }}</td>
                    <td class="user-name">{{ user.username }}</td>
                    <td>{{ user.roles[0]|trans }}</td>
                    <td>
                        {% if user.connectionTimestamp %}
                            {{ user.connectionTimestamp|date('d/m/Y H:i:s') }}
                        {% else %}
                            {{ 'users.lastConnectionNone'|trans }}
                        {% endif %}
                    </td>
                    <td class="text-right user-buttons">
                        <button class="btn btn-xs btn-default user-reset-password">
                            <span class="fa fa-undo"></span>
                        </button>

                        {% if user.id != userId %}
                        <a class="btn btn-xs btn-default user-switch" href="{{ path('listFiles', { _switch_user: user.username, _prefixId: 'files' }) }}">
                            <span class="fa fa-exchange-alt"></span>
                        </a>
                            {% if user.id != 1 %}
                        <button class="btn btn-xs btn-danger user-remove">
                            <span class="fa fa-times"></span>
                        </button>
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>
                {% endcache %}
            {% endfor %}
        </tbody>
    </table>

    {% include "fragments/pagination.html.twig" %}

{% endblock %}

templates/pages/playFile.html.twig
{% extends 'skeleton.html.twig' %}

{% block title %}{{ name }} - {{ 'app.name'|trans }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('media') }}
{% endblock %}

{% block main_script %}
    {{ encore_entry_script_tags('media') }}
{% endblock %}

{% block content %}
    <h1 title="{{ name }}">{{ name }}</h1>

    {% include 'fragments/breadcrumb.html.twig' %}

    <div class="media-container">
        <{{ mediaTag }} autoplay controls>
            <source type="{{ type }}" src="{{ path('openFile', { path: src }) }}" />
        </{{ mediaTag }}>
    </div>
{% endblock %}

templates/pages/showSearch.html.twig
{% extends 'skeleton.html.twig' %}

{% block title %}{{ 'search.title'|trans }} - {{ 'app.name'|trans }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('search') }}
{% endblock %}

{% block main_script %}
    {{ encore_entry_script_tags('search') }}
{% endblock %}

{% block content %}
    <form method="get" class="input-group search-control">
        <select class="form-control" name="source">
            <option value="all"{% if source == 'all' %} selected{% endif %}>{{ 'search.all-sources'|trans }}</option>
            {% for s in sources %}
                <option value="{{ s.id }}"{% if s.id == source %} selected{% endif %}>{{ s.name }}</option>
            {% endfor %}
        </select>
        <div class="input-expander">
            <input type="text" class="form-control" name="q" placeholder="{{ 'search.keywords'|trans }}" value="{{ query }}" />
        </div>
        <span class="input-group-btn">
            <button class="btn btn-default">{{ 'search.submit'|trans }}</button>
        </span>
    </form>

    {% if query is not empty %}
        {% if results is empty %}
            <div class="alert alert-info" role="alert">{{ 'search.no-results'|trans }}</div>
        {% else %}
            {% include 'fragments/searchResults.html.twig' %}
        {% endif %}
    {% endif %}
{% endblock %}